
default:
#	export TEST_DIR=${HOME}/code_development/pgfem3d/pgfem3d
#	export PGFEM3D_EXT_LIB=${HOME}/lib/external
	@echo ${pgfem_root_dir}
	(cd src ; make )

clean:
	(rm -f *.txt)
	(cd src ; make clean )
